# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
