# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0002_rate_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='average',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='care',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='efficiency',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='response',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
