# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0002_auto_20181025_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
