# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0003_auto_20181025_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='moving.Services'),
        ),
    ]
