# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('moving', '0006_auto_20181026_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('location', models.TextField(max_length=50, null=True)),
                ('number', models.TextField(max_length=50, null=True)),
                ('email', models.TextField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='moving.Payment')),
            ],
        ),
    ]
